### PR TITLE
153 - Upload a picture into a document

### LINKED ISSUE #153: Upload a picture into a document
For now, it is possible from a document to refer to a picture in Markdown:
```
![Description](https://elsewhere/MyPicture)
```
However this picture must be already on a distant server.

The idea, for example, would be to drag and drop a picture (like in GitHub issues or discussions). It would be then stored in CouchDB as an attached file of the document chunk and a markdown reference would be automatically created in the document.

### PR DESCRIPTION
**Pull request by raphaelweis**
We, Raphaël WEIS, Fabien PETIT, Barnabé PETIT, Louis DUHALBERRUER, Martin GANDON, hereby grant to Hyperglosae maintainers the right to publish our contribution under the terms of any licenses the Free Software Foundation classifies as Free Software Licenses.

Closes #153.

### CODE REVIEW

**Comment by raphaelweis** [comment]
The implementation for uploading an image, and the associated test is working as well.
I think some tests are broken following some css adjustments I had to make, I will work on fixing those on friday.
Additionally, this branch hasn't been updated for 3 weeks, resulting in a merge conflict with main that will need to be addressed.

**Review by benel — APPROVED** [review]
Well done @raphaelweis, @nitram35, @petitfa1, @barnabepetit, feature 153 ("Upload...") is ready to be integrated! 🎉

**Review by benel — CHANGES_REQUESTED** [review]
Errm. Maybe I wrote too fast...
Could your please fix the CSS rules that broke the tooltip position?

Main branch:
Capture d’écran 2024-06-08 à 12 07 30

Feature-153 branch:
Capture d’écran 2024-06-08 à 12 06 36

**Comment by raphaelweis** [comment]
Turns out I went too fast after refactoring my CSS file. I have added an import for my css file at the top of `PassageMarginMenu` and I've updated the CSS to use the class `content` instead of `editable` to prevent the changes from affecting the glose metadata layout.

Additionally, I've updated the branch with the latest commits on main, and I've changed the placeholder for the alt text of new images from the image name to `<IMAGE DESCRIPTION>`.

**Comment by benel** [comment]
Integrated as 597670f27dca514e9c4f5f4f5d4288c3e53e5a25 🎉 

Well done @raphaelweis @nitram35 @petitfa1 @Barnabepetit!!!

Thank you for your contribution!

**Pull request closed without merging**
